name: Deploy Flask App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          if [ ! -d "~/sprint2/.git" ]; then
            git clone git@github.com:krafton-jungle-sprint-2/release.git
            cd ~/release
          else
            cd ~/release
            git pull origin main
          fi

          docker compose down || true
          docker compose up -d --build